# Generated by Django 6.0.6 on 2026-06-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0002_remove_aboutdahanraj_course_dis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mpsccourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=500)),
                ('course_name', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=200)),
                ('fees', models.CharField(max_length=300)),
                ('timing', models.DateField()),
                ('mode', models.CharField(max_length=200)),
            ],
        ),
    ]
