# Generated by Django 6.0.6 on 2026-06-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0003_mpsccourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsccourse',
            name='timing',
            field=models.CharField(max_length=300),
        ),
    ]
