# Generated by Django 6.0.6 on 2026-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0004_alter_mpsccourse_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpsccourse',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
