# Generated by Django 6.0.6 on 2026-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0005_mpsccourse_show_on_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=1000)),
                ('eligibility', models.CharField(max_length=1000)),
                ('fees', models.CharField(max_length=500)),
                ('benefit1', models.CharField(max_length=1000)),
                ('benefit2', models.CharField(max_length=1000)),
                ('benefit3', models.CharField(max_length=1000)),
                ('benefit4', models.CharField(max_length=1000)),
                ('benefit5', models.CharField(max_length=1000)),
                ('admission_notice', models.TextField()),
            ],
        ),
    ]
