# Generated by Django 6.0.6 on 2026-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0006_courseinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courseinfo',
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='admission_notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='benefit1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='benefit2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='benefit3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='benefit4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='benefit5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='eligibility',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='heading',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
