# Generated by Django 6.0.6 on 2026-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0007_delete_courseinfo_mpsccourse_admission_notice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpsccourse',
            name='mode',
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='extra_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpsccourse',
            name='extra_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
