# Generated by Django 6.0.6 on 2026-06-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0008_remove_mpsccourse_mode_mpsccourse_extra_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='static/ad/images/')),
                ('academy_name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('facebook', models.CharField(max_length=500)),
                ('linkdin', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
            ],
        ),
    ]
