# Generated by Django 6.0.6 on 2026-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy_Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_title', models.CharField(max_length=500)),
                ('statistic_count', models.IntegerField(default=0)),
                ('statistic_icon', models.CharField(max_length=500)),
            ],
        ),
    ]
