# Generated by Django 6.0.6 on 2026-06-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0010_academy_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Profilesdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/ad/images/')),
                ('fullname', models.CharField(max_length=500)),
                ('traner', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('linkedin', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
            ],
        ),
    ]
