# Generated by Django 6.0.6 on 2026-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0011_teacher_profilesdahanraj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/ad/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('upload_book', models.FileField(upload_to='static/ad/images/')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=500)),
                ('about_description', models.TextField()),
                ('vision_description', models.TextField()),
                ('year1', models.CharField(max_length=20)),
                ('timeline1', models.TextField()),
                ('year2', models.CharField(max_length=20)),
                ('timeline2', models.TextField()),
                ('year3', models.CharField(max_length=20)),
                ('timeline3', models.TextField()),
                ('year4', models.CharField(max_length=20)),
                ('timeline4', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_aboutdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('dec_1', models.CharField(max_length=500)),
                ('dec_2', models.CharField(max_length=500)),
                ('dec_3', models.CharField(max_length=500)),
                ('para', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_AskedQdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=700)),
                ('ans', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_carddahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('dec', models.CharField(max_length=500)),
                ('para', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_faqdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('dec', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Locationsdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('dec', models.CharField(max_length=500)),
                ('academy_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=500)),
                ('add', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_usdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('dec', models.CharField(max_length=500)),
                ('sub_btn', models.CharField(max_length=500)),
                ('always', models.CharField(max_length=500)),
                ('para', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Demo_Sessionsdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('dec', models.CharField(max_length=2000)),
                ('sub_btn', models.CharField(max_length=2000)),
                ('sub_dec', models.CharField(max_length=2000)),
                ('sub_video', models.FileField(upload_to='static/ad/videos')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Police Bharti', 'Police Bharti'), ('Talathi', 'Talathi'), ('Gramsevak', 'Gramsevak'), ('Vanrakshak', 'Vanrakshak'), ('MPSC', 'MPSC')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/ad/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Latestpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Notification', 'Notification'), ('Result', 'Result'), ('New Batch', 'New Batch'), ('Admission', 'Admission'), ('Event', 'Event')], max_length=50, null=True)),
                ('heading', models.CharField(max_length=500)),
                ('heading_description', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(upload_to='static/ad/images/')),
                ('badge_text', models.CharField(blank=True, max_length=300, null=True)),
                ('hero_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('hero_description', models.TextField(blank=True, null=True)),
                ('overview_title', models.CharField(blank=True, max_length=500, null=True)),
                ('overview_description', models.TextField(blank=True, null=True)),
                ('physical_title', models.CharField(blank=True, max_length=500, null=True)),
                ('physical_point_1', models.CharField(blank=True, max_length=500, null=True)),
                ('physical_point_2', models.CharField(blank=True, max_length=500, null=True)),
                ('physical_point_3', models.CharField(blank=True, max_length=500, null=True)),
                ('physical_point_4', models.CharField(blank=True, max_length=500, null=True)),
                ('physical_point_5', models.CharField(blank=True, max_length=500, null=True)),
                ('written_title', models.CharField(blank=True, max_length=500, null=True)),
                ('written_point_1', models.CharField(blank=True, max_length=500, null=True)),
                ('written_point_2', models.CharField(blank=True, max_length=500, null=True)),
                ('written_point_3', models.CharField(blank=True, max_length=500, null=True)),
                ('written_point_4', models.CharField(blank=True, max_length=500, null=True)),
                ('written_point_5', models.CharField(blank=True, max_length=500, null=True)),
                ('selection_title', models.CharField(blank=True, max_length=500, null=True)),
                ('selection_description', models.TextField(blank=True, null=True)),
                ('step1_title', models.CharField(blank=True, max_length=500, null=True)),
                ('step1_description', models.TextField(blank=True, null=True)),
                ('step2_title', models.CharField(blank=True, max_length=500, null=True)),
                ('step2_description', models.TextField(blank=True, null=True)),
                ('step3_title', models.CharField(blank=True, max_length=500, null=True)),
                ('step3_description', models.TextField(blank=True, null=True)),
                ('step4_title', models.CharField(blank=True, max_length=500, null=True)),
                ('step4_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Police', 'Police'), ('Gramsevak', 'Gramsevak'), ('Vanrakshak', 'Vanrakshak'), ('MPSC', 'MPSC'), ('Talathi', 'Talathi')], max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/ad/images/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('posting', models.CharField(default='Not Specified', max_length=255)),
                ('preparation', models.CharField(blank=True, max_length=255, null=True)),
                ('success_journey', models.TextField(blank=True, null=True)),
                ('daily_routine', models.TextField(blank=True, null=True)),
                ('student_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_number', models.CharField(max_length=100)),
                ('students_label', models.CharField(max_length=100)),
                ('selection_number', models.CharField(max_length=100)),
                ('selection_label', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('batch_label', models.CharField(max_length=100)),
                ('course_number', models.CharField(max_length=100)),
                ('course_label', models.CharField(max_length=100)),
                ('experience_number', models.CharField(max_length=100)),
                ('experience_label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Reviewsdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/ad/images/')),
                ('fullname', models.CharField(max_length=500)),
                ('traner', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=500)),
                ('dec', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subjectdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('dec', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
