# Generated by Django 6.0.6 on 2026-06-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0012_blog_books_competitionabout_contact_aboutdahanraj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
    ]
