# Generated by Django 6.0.6 on 2026-06-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('occupation', models.CharField(max_length=300)),
                ('qualification', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('batch', models.CharField(max_length=300)),
            ],
        ),
    ]
