# Generated by Django 6.0.6 on 2026-06-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enroll',
            new_name='StudentEnroll',
        ),
    ]
