# Generated by Django 6.0.6 on 2026-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_enroll_studentenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_callbackdahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cb_name', models.CharField(max_length=500)),
                ('cb_mobile', models.CharField(max_length=500)),
                ('cb_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_form_tabledahanraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
                ('mess', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='studentenroll',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
