# Generated by Django 6.0.6 on 2026-06-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contact_callbackdahanraj_contact_form_tabledahanraj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenroll',
            name='status',
        ),
    ]
